eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.application.name=api-gateway

#increase logging level
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
#RouteDefinitionLocator- this is the class which is responsible for define the routes and identify the routes for the incoming request
logging.level.org.springframework.cloud.gateway=TRACE
#TRACE-can understand what is going on behind the scenes whenever a request made to a api gateway


#Product Service Route
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product/**

#Order Service Route
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://order-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order

#inventory Service Route
spring.cloud.gateway.routes[2].id=inventory-service
spring.cloud.gateway.routes[2].uri=lb://inventory-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventory

#Discovery server Route
spring.cloud.gateway.routes[3].id=discovery-server
spring.cloud.gateway.routes[3].uri=http://localhost:8761
spring.cloud.gateway.routes[3].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[3].filters[0]=SetPath=/

#Discovery static server Route
spring.cloud.gateway.routes[4].id=discovery-server
spring.cloud.gateway.routes[4].uri=http://localhost:8761
spring.cloud.gateway.routes[4].predicates[0]=Path=/eureka/**

jwt.secret=MyVerySecretKeyForJwtAuthentication123456789


#redis for rate limiting
spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=1
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=2
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}


logging.level.org.springframework.cloud.gateway.filter.ratelimit=TRACE
logging.level.org.springframework.data.redis=DEBUG

#to test rate limiting
#for i in {1..20}; do curl -i -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBa3NoYWRhMyIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3ODU4Njc2MjEsImV4cCI6MTc4NTg3MTIyMX0.pqLTDJY6GqQlsSi8kFkfV86pYVbMOdsZJfk_XNmggYg" http://localhost:8080/api/product; echo; done

#retry pattern
spring.cloud.gateway.routes[0].filters[1].name=Retry
spring.cloud.gateway.routes[0].filters[1].args.retries=3
spring.cloud.gateway.routes[0].filters[1].args.methods=GET
spring.cloud.gateway.routes[0].filters[1].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT,INTERNAL_SERVER_ERROR,SERVICE_UNAVAILABLE

#Circuit breaker pattern
spring.cloud.gateway.routes[0].filters[2].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[2].args.name=productCircuit
spring.cloud.gateway.routes[0].filters[2].args.fallbackUri=forward:/fallback/product
resilience4j.circuitbreaker.instances.productCircuit.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.productCircuit.slidingWindowSize=2
resilience4j.circuitbreaker.instances.productCircuit.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.productCircuit.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productCircuit.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productCircuit.permittedNumberOfCallsInHalfOpenState=1

logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.io.github.resilience4j=DEBUG
