spring.data.mongodb.uri=${MONGODB_URI:mongodb://mongodb:27017/product-service}
server.port=${SERVER_PORT:8080}

#Eureka server
spring.application.name=product-service
#eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://discovery-server:8761/eureka}